In [1]:
import numpy as np

In [2]:
np.ones((30,))/30

array([ 0.03333333,  0.03333333,  0.03333333,  0.03333333,  0.03333333,
        0.03333333,  0.03333333,  0.03333333,  0.03333333,  0.03333333,
        0.03333333,  0.03333333,  0.03333333,  0.03333333,  0.03333333,
        0.03333333,  0.03333333,  0.03333333,  0.03333333,  0.03333333,
        0.03333333,  0.03333333,  0.03333333,  0.03333333,  0.03333333,
        0.03333333,  0.03333333,  0.03333333,  0.03333333,  0.03333333])

In [3]:
np.ones(30)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.])

In [4]:
np.ones(30)/30

array([ 0.03333333,  0.03333333,  0.03333333,  0.03333333,  0.03333333,
        0.03333333,  0.03333333,  0.03333333,  0.03333333,  0.03333333,
        0.03333333,  0.03333333,  0.03333333,  0.03333333,  0.03333333,
        0.03333333,  0.03333333,  0.03333333,  0.03333333,  0.03333333,
        0.03333333,  0.03333333,  0.03333333,  0.03333333,  0.03333333,
        0.03333333,  0.03333333,  0.03333333,  0.03333333,  0.03333333])

In [5]:
a = np.random.rand(300)*100

In [6]:
a

array([  3.66745032e+01,   5.69283722e+01,   2.87082923e+01,
         4.72615439e+01,   5.40972881e+00,   7.09865423e+01,
         4.10485069e+01,   1.98829770e+01,   2.49668003e+01,
         8.78924186e+00,   9.87015670e+01,   9.33027404e+01,
         6.63077442e+01,   8.62102821e+01,   8.11838276e+01,
         1.73138393e+01,   7.26265585e+01,   5.68337194e+01,
         6.35902242e+01,   3.13864094e+00,   5.77579554e+01,
         2.59253678e+01,   8.28839813e+01,   9.41613689e+00,
         2.45502909e+01,   5.64437980e+01,   9.16754273e+01,
         7.64483644e+01,   6.35060560e+01,   4.95100420e+00,
         7.99179555e+01,   5.34597307e+01,   4.67298510e+01,
         4.97335405e+01,   7.89433663e+01,   1.94890738e+01,
         8.26751139e+01,   2.10502478e+01,   8.84127724e+01,
         5.02307920e+01,   4.46125890e+01,   2.96913396e+01,
         2.17482566e+01,   8.27408375e+01,   2.22984459e+01,
         5.65908205e+01,   9.20774707e+00,   9.63727965e+00,
         8.73232372e+01,